### ISSUE TITLE
Syntax highlighting broken on package declaration

### ISSUE THREAD

**Issue by snjeza** [atom/language-java#140]
Steps to reproduce:

Try opening the following file:

```
package org.sample.EDU;

public class Test {
}
```

Capital letters are marked as an error:

![140](https://user-images.githubusercontent.com/388609/40625317-ed9c3a10-62b1-11e8-90bf-c7e01770f5c7.png)

See https://github.com/redhat-developer/vscode-java/issues/351 and https://docs.oracle.com/javase/specs/jls/se6/html/packages.html#7.7

**Comment by thomasjo** [comment]
I agree with @sadikovi. This has been discussed before, and we made a decision then that has not been changed since then.

If you disagree with our decision to mark this as invalid syntax, you can add something like the following to your custom stylesheet (`~/.atom/styles.cson`) to negate the default styling
```less
.syntax--java.syntax--package_name_not_lowercase {
  background-color: inherit !important;
  color: inherit !important;
}

```
